type UniverseItem = {
  symbol: string;
  name: string;
  sector: string;
  marketCapB: number;
};

// Approximate market caps (USD billions) to size tiles without extra API calls.
export const HEATMAP_UNIVERSE: UniverseItem[] = [
  { symbol: "MSFT", name: "Microsoft", sector: "Technology", marketCapB: 3150 },
  { symbol: "AAPL", name: "Apple", sector: "Technology", marketCapB: 2900 },
  { symbol: "NVDA", name: "NVIDIA", sector: "Technology", marketCapB: 2400 },
  { symbol: "GOOGL", name: "Alphabet", sector: "Communication Services", marketCapB: 2100 },
  { symbol: "AMZN", name: "Amazon", sector: "Consumer Discretionary", marketCapB: 1900 },
  { symbol: "META", name: "Meta Platforms", sector: "Communication Services", marketCapB: 1300 },
  { symbol: "BRK.B", name: "Berkshire Hathaway", sector: "Financials", marketCapB: 920 },
  { symbol: "LLY", name: "Eli Lilly", sector: "Healthcare", marketCapB: 780 },
  { symbol: "AVGO", name: "Broadcom", sector: "Technology", marketCapB: 700 },
  { symbol: "TSLA", name: "Tesla", sector: "Consumer Discretionary", marketCapB: 710 },
  { symbol: "V", name: "Visa", sector: "Financials", marketCapB: 560 },
  { symbol: "JPM", name: "JPMorgan Chase", sector: "Financials", marketCapB: 550 },
  { symbol: "WMT", name: "Walmart", sector: "Consumer Staples", marketCapB: 500 },
  { symbol: "MA", name: "Mastercard", sector: "Financials", marketCapB: 470 },
  { symbol: "UNH", name: "UnitedHealth", sector: "Healthcare", marketCapB: 470 },
  { symbol: "XOM", name: "Exxon Mobil", sector: "Energy", marketCapB: 430 },
  { symbol: "ORCL", name: "Oracle", sector: "Technology", marketCapB: 430 },
  { symbol: "COST", name: "Costco", sector: "Consumer Staples", marketCapB: 390 },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Healthcare", marketCapB: 380 },
  { symbol: "HD", name: "Home Depot", sector: "Consumer Discretionary", marketCapB: 370 },
  { symbol: "PG", name: "Procter & Gamble", sector: "Consumer Staples", marketCapB: 370 },
  { symbol: "TCEHY", name: "Tencent", sector: "Communication Services", marketCapB: 350 },
  { symbol: "MRK", name: "Merck", sector: "Healthcare", marketCapB: 320 },
  { symbol: "AMD", name: "Advanced Micro Devices", sector: "Technology", marketCapB: 320 },
  { symbol: "ABBV", name: "AbbVie", sector: "Healthcare", marketCapB: 300 },
  { symbol: "CRM", name: "Salesforce", sector: "Technology", marketCapB: 300 },
  { symbol: "BAC", name: "Bank of America", sector: "Financials", marketCapB: 280 },
  { symbol: "CVX", name: "Chevron", sector: "Energy", marketCapB: 280 },
  { symbol: "ADBE", name: "Adobe", sector: "Technology", marketCapB: 260 },
  { symbol: "NFLX", name: "Netflix", sector: "Communication Services", marketCapB: 250 },
  { symbol: "PEP", name: "PepsiCo", sector: "Consumer Staples", marketCapB: 250 },
  { symbol: "TMUS", name: "T-Mobile", sector: "Communication Services", marketCapB: 220 },
  { symbol: "MCD", name: "McDonald's", sector: "Consumer Discretionary", marketCapB: 220 },
  { symbol: "TMO", name: "Thermo Fisher", sector: "Healthcare", marketCapB: 220 },
  { symbol: "CSCO", name: "Cisco", sector: "Technology", marketCapB: 220 },
  { symbol: "BABA", name: "Alibaba", sector: "Consumer Discretionary", marketCapB: 200 },
  { symbol: "QCOM", name: "Qualcomm", sector: "Technology", marketCapB: 200 },
  { symbol: "PDD", name: "PDD Holdings", sector: "Consumer Discretionary", marketCapB: 190 },
  { symbol: "IBM", name: "IBM", sector: "Technology", marketCapB: 180 },
  { symbol: "NOW", name: "ServiceNow", sector: "Technology", marketCapB: 180 },
  { symbol: "DIS", name: "Walt Disney", sector: "Communication Services", marketCapB: 180 },
  { symbol: "GE", name: "GE Aerospace", sector: "Industrials", marketCapB: 170 },
  { symbol: "UBER", name: "Uber", sector: "Industrials", marketCapB: 170 },
  { symbol: "VZ", name: "Verizon", sector: "Communication Services", marketCapB: 170 },
  { symbol: "CAT", name: "Caterpillar", sector: "Industrials", marketCapB: 170 },
  { symbol: "PFE", name: "Pfizer", sector: "Healthcare", marketCapB: 160 },
  { symbol: "NKE", name: "Nike", sector: "Consumer Discretionary", marketCapB: 150 },
  { symbol: "PANW", name: "Palo Alto Networks", sector: "Technology", marketCapB: 130 },
  { symbol: "COP", name: "ConocoPhillips", sector: "Energy", marketCapB: 130 },
  { symbol: "T", name: "AT&T", sector: "Communication Services", marketCapB: 130 },
  { symbol: "SHOP", name: "Shopify", sector: "Technology", marketCapB: 120 },
  { symbol: "BA", name: "Boeing", sector: "Industrials", marketCapB: 120 },
  { symbol: "VRTX", name: "Vertex", sector: "Healthcare", marketCapB: 120 },
  { symbol: "REGN", name: "Regeneron", sector: "Healthcare", marketCapB: 110 },
  { symbol: "DE", name: "Deere", sector: "Industrials", marketCapB: 110 },
  { symbol: "GILD", name: "Gilead", sector: "Healthcare", marketCapB: 100 },
  { symbol: "PBR", name: "Petrobras", sector: "Energy", marketCapB: 95 },
  { symbol: "PLTR", name: "Palantir", sector: "Technology", marketCapB: 75 },
  { symbol: "SNOW", name: "Snowflake", sector: "Technology", marketCapB: 75 },
  { symbol: "PYPL", name: "PayPal", sector: "Financials", marketCapB: 70 },
  { symbol: "IWM", name: "iShares Russell 2000 ETF", sector: "ETF", marketCapB: 70 },
  { symbol: "SLB", name: "Schlumberger", sector: "Energy", marketCapB: 65 },
  { symbol: "XLK", name: "Technology Select Sector ETF", sector: "ETF", marketCapB: 60 },
  { symbol: "COIN", name: "Coinbase", sector: "Financials", marketCapB: 60 },
  { symbol: "GM", name: "General Motors", sector: "Consumer Discretionary", marketCapB: 55 },
  { symbol: "OXY", name: "Occidental Petroleum", sector: "Energy", marketCapB: 55 },
  { symbol: "F", name: "Ford", sector: "Consumer Discretionary", marketCapB: 50 },
  { symbol: "XLV", name: "Healthcare Select Sector ETF", sector: "ETF", marketCapB: 45 },
  { symbol: "MSTR", name: "MicroStrategy", sector: "Technology", marketCapB: 45 },
  { symbol: "XLF", name: "Financial Select Sector ETF", sector: "ETF", marketCapB: 40 },
  { symbol: "XLE", name: "Energy Select Sector ETF", sector: "ETF", marketCapB: 35 },
  { symbol: "DIA", name: "SPDR Dow Jones ETF", sector: "ETF", marketCapB: 35 },
  { symbol: "RBLX", name: "Roblox", sector: "Communication Services", marketCapB: 30 },
  { symbol: "QQQ", name: "Invesco QQQ ETF", sector: "ETF", marketCapB: 280 },
  { symbol: "SPY", name: "SPDR S&P 500 ETF", sector: "ETF", marketCapB: 500 },
  { symbol: "NIO", name: "NIO", sector: "Consumer Discretionary", marketCapB: 20 },
  { symbol: "HOOD", name: "Robinhood", sector: "Financials", marketCapB: 20 },
  { symbol: "SOFI", name: "SoFi", sector: "Financials", marketCapB: 12 },
  { symbol: "RIVN", name: "Rivian", sector: "Consumer Discretionary", marketCapB: 12 },
  { symbol: "LCID", name: "Lucid", sector: "Consumer Discretionary", marketCapB: 8 }
];
